### ISSUE TITLE
Font Size Issues

### ISSUE THREAD

**Issue by ClaireReinken** [FEISystems/ms-macwis-prototype#110]
On the search results page, the font size for the data is larger than the labels. For example, "Type:
Center". Center is larger than Type.

**Comment by christianhfei** [comment]
This is intentional. If we'd like to keep them all the same, that's fine, but I think it helps to have these different for readability.

**Comment by ClaireReinken** [comment]
Hatem pointed it out. Can we keep it the same size font for the results and labels?

Thanks!
- Claire Reinken

On Oct 6, 2016, at 7:52 PM, christianhfei <notifications@github.com<mailto:notifications@github.com>> wrote:

This is intentional. If we'd like to keep them all the same, that's fine, but I think it helps to have these different for readability.

##

**Comment by lutech** [comment]
Hi Claire, I think its best to keep the size different so that it is easier to distinguish the label vs data. This is common practice through out the web and helps with readability. If anything, I'd prefer to make the data or value slightly bigger so that it seems more intentional rather than a bug.

**Comment by ClaireReinken** [comment]
That's fine. I am going to close the issue.
